### ISSUE TITLE
Implement Property Changed Tracker Classes With Undo/Redo Support

### ISSUE THREAD

**Issue by oshelton** [oshelton/WPFAspects#3]
A simple class that tracks property value changes and allows for them to be reversed needs to be created.

This class should have the following features:
*  Can keep track of changes to multiple objects (including the order in which they were made).
*  Makes it possible to undo and redo changes (redo will be the trickier of the two).

* [ ]  Implement commands for undo/redo.
* [ ]  Add support for tracking Observable collections.
* [ ]  Create tests for this class.
